### ISSUE TITLE
Word "Last saved by" and "Last modified by"

### ISSUE THREAD

**Issue by Rvnd0m** [sh1d0wg1m3r/Metadata-Removal-Tool#1]
Hi Svetozar,

First of all, thank you for your development.

I have tried the py on a Word file, and it works properly for easing the Author. However, it doesn't remove the "Last modified by" field when I check it on the tab File > Info, neither when I right-click on the file > Properties > Details tab, Origin section, and there, the "Last saved by" is also the same person.

Is there any solution for that? I mean, to leave it blank, or if it would not be possible to keep it blank, at least fill that field with an space or something like that.

Thank you again,

**Comment by sh1d0wg1m3r** [comment]
Sorry I am full of homework. Yes it can be solved ( just need to troubleshoot my shitty code ). I will solve it in 2 hours. Also thanks for visiting my project

**Comment by sh1d0wg1m3r** [comment]
done. Turns out I forgor 
doc.core_properties.last_modified_by = ""

**Comment by Rvnd0m** [comment]
Hi Svetozar, thank you for your reply!

I have already tried adding that line on the py DOCX function (after the author line) before opening the topic, but it saw not to work (at least on my computer, Win10 Pro). Does it work on yours?? Just to spot if the problem is my pc or that that line doesn't erases the last saved by / last modified by.

Regards,

**Comment by sh1d0wg1m3r** [comment]
What version of office do you have installed? Also it works on my end ( office 2019 ). Also is there a compatibility option you have enabled or anything that changes the file in unexpected ways?

**Comment by Rvnd0m** [comment]
Hi Svetozar.
1st of all, sorry for my delay on replies... lot of work this days!

You have updated the code, right?? It works fine now! I've tried the new code with Python3.11, also running a MS Office 2019 Pro version, and now it removes the "las saved by" field too.

So thank you for your code, your kindness and your time :)

Regards,
